name: triomino_core
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.14.0 <3.0.0'


dev_dependencies:
  build_runner: ^2.1.2
  freezed: ^0.14.5
  lints: ^1.0.0
dependencies:
  freezed_annotation: ^0.14.3
