name: triomino_core
# TODO: improve description
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'


dev_dependencies:
  build_runner: ^2.1.2
  freezed: ^2.0.3+1
  lints: ^2.0.0
  test: ^1.17.12
  test_process: ^2.0.2
dependencies:
  collection: ^1.16.0
  freezed_annotation: ^2.0.3
